---
abstract: 'Hook system with asynchronous capabilities'
author:
  - 'Pedro Melo <melo@cpan.org>'
build_requires:
  Test::Deep: 0
  Test::Exception: 0
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.79'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Async-Hooks
no_index:
  directory:
    - inc
    - t
requires:
  Mouse: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/melo/perl-async-hooks/
version: 0.01
